version: "3.8"
services:
  db:
    build: ./evoca-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - mysql:/var/lib/mysql
  api:
    build: ./evoca-backend
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    depends_on:
      - db
    restart: on-failure
  frontend:
    container_name: frontend
    build: ./evoca-frontend
    volumes:
      - "./:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
volumes:
  mysql:
